// js-framework-benchmark/frameworks/keyed/preact-signals/src/main.jsx
import { signal, batch, useComputed } from "@preact/signals";
import { For } from "@preact/signals/utils";
import { render, h } from "preact";

let idCounter = 1;
const adjectives = [
    "pretty",
    "large",
    "big",
    "small",
    "tall",
    "short",
    "long",
    "handsome",
    "plain",
    "quaint",
    "clean",
    "elegant",
    "easy",
    "angry",
    "crazy",
    "helpful",
    "mushy",
    "odd",
    "unsightly",
    "adorable",
    "important",
    "inexpensive",
    "cheap",
    "expensive",
    "fancy",
  ],
  colours = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"],
  nouns = [
    "table",
    "chair",
    "house",
    "bbq",
    "desk",
    "car",
    "pony",
    "cookie",
    "sandwich",
    "burger",
    "pizza",
    "mouse",
    "keyboard",
  ];

function _random(max) {
  return Math.round(Math.random() * 1000) % max;
}

function buildData(count) {
  let data = new Array(count);
  for (let i = 0; i < count; i++) {
    const label = signal(
      `${adjectives[_random(adjectives.length)]} ${colours[_random(colours.length)]} ${nouns[_random(nouns.length)]}`
    );
    data[i] = {
      id: idCounter++,
      label,
    };
  }
  return data;
}

const Button = ({ id, text, fn }) => (
  <div class="col-sm-6 smallpad">
    <button id={id} class="btn btn-primary btn-block" type="button" onClick={fn}>
      {text}
    </button>
  </div>
);
const data = signal([]);
const selected = signal(null);

const run = () => {
    data.value = buildData(1000);
  },
  runlots = () => (data.value = buildData(10000)),
  add = () => {
    data.value = data.value.concat(buildData(1000));
  },
  update = () =>
    batch(() => {
      for (let i = 0, d = data.value, len = d.length; i < len; i += 10) {
        d[i].label.value = d[i].label.value + " !!!";
      }
    }),
  swaprows = () => {
    const d = data.value.slice();
    if (d.length > 998) {
      let tmp = { ...d[1] };
      d[1] = { ...d[998] };
      d[998] = tmp;
      data.value = d;
    }
  },
  clear = () => (data.value = []),
  remove = (id) => {
    const idx = data.value.findIndex((d) => d.id === id);
    data.value = [...data.value.slice(0, idx), ...data.value.slice(idx + 1)];
  },
  select = (id) => {
    selected.value = id;
  };

const Row = ({ id, label }) => {
  const rowClass = useComputed(() => (selected.value === id ? "danger" : ""));
  return (
    <tr class={rowClass}>
      <td class="col-md-1" textContent={id} />
      <td class="col-md-4">
        <a onClick={() => select(id)} textContent={label} />
      </td>
      <td class="col-md-1">
        <a onClick={() => remove(id)}>
          <span class="glyphicon glyphicon-remove" aria-hidden="true" />
        </a>
      </td>
      <td class="col-md-6" />
    </tr>
  );
};

const App = () => {
  return (
    <div class="container">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-6">
            <h1>Preact Signals Keyed</h1>
          </div>
          <div class="col-md-6">
            <div class="row">
              <Button id="run" text="Create 1,000 rows" fn={run} />
              <Button id="runlots" text="Create 10,000 rows" fn={runlots} />
              <Button id="add" text="Append 1,000 rows" fn={add} />
              <Button id="update" text="Update every 10th row" fn={update} />
              <Button id="clear" text="Clear" fn={clear} />
              <Button id="swaprows" text="Swap Rows" fn={swaprows} />
            </div>
          </div>
        </div>
      </div>
      <table class="table-hover table-striped test-data table">
        <tbody>
          <For each={data}>{(row) => <Row key={row.id} id={row.id} label={row.label} />}</For>
        </tbody>
      </table>
      <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true" />
    </div>
  );
};

render(<App />, document.getElementById("main"));

// js-framework-benchmark/frameworks/keyed/vanillajs-wc/src/main.js
const ADJECTIVES = [
  "pretty",
  "large",
  "big",
  "small",
  "tall",
  "short",
  "long",
  "handsome",
  "plain",
  "quaint",
  "clean",
  "elegant",
  "easy",
  "angry",
  "crazy",
  "helpful",
  "mushy",
  "odd",
  "unsightly",
  "adorable",
  "important",
  "inexpensive",
  "cheap",
  "expensive",
  "fancy",
];
const COLOURS = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"];
const NOUNS = [
  "table",
  "chair",
  "house",
  "bbq",
  "desk",
  "car",
  "pony",
  "cookie",
  "sandwich",
  "burger",
  "pizza",
  "mouse",
  "keyboard",
];

let _nextId = 1;
function buildData(count) {
  const data = [];

  for (let i = 0; i < count; i++) {
    data.push({
      id: _nextId++,
      label: `${ADJECTIVES[_random(ADJECTIVES.length)]} ${COLOURS[_random(COLOURS.length)]} ${NOUNS[_random(NOUNS.length)]}`,
    });
  }

  return data;
}

function _random(max) {
  return Math.round(Math.random() * 1000) % max;
}

class Store {
  constructor() {
    this.data = [];
    this.selected = null;
  }

  run() {
    this.data = buildData(1000);
    this.selected = null;
  }

  runlots() {
    this.data = buildData(10000);
    this.selected = null;
  }

  add() {
    this.data = this.data.concat(buildData(1000));
    this.selected = null;
  }

  update() {
    for (let i = 0; i < this.data.length; i += 10) {
      this.data[i].label += " !!!";
    }
    this.selected = null;
  }

  clear() {
    this.data = [];
    this.selected = null;
  }

  swaprows() {
    if (this.data.length > 998) {
      const a = this.data[1];
      this.data[1] = this.data[998];
      this.data[998] = a;
    }
  }

  delete(id) {
    this.data = this.data.filter((d) => d.id !== id);
  }

  select(id) {
    this.selected = id;
  }
}

class BenchmarkApp extends HTMLDivElement {
  constructor() {
    super();
    this._store = new Store();
    this._rows = [];
    this._selectedRow = null;

    this.id = "main";

    const container = document.createElement("div");
    container.className = "container";
    const jumbotron = document.createElement("div");
    jumbotron.className = "jumbotron";
    const jumbotronRow = document.createElement("div");
    jumbotronRow.className = "row";

    // title
    const titleDiv = document.createElement("div");
    titleDiv.className = "col-md-6";
    const titleH1 = document.createElement("h1");
    titleH1.textContent = "VanillaJS-WC-keyed";

    titleDiv.appendChild(titleH1);

    // menu
    const menuDiv = document.createElement("div");
    menuDiv.className = "col-md-6";
    const menuRow = document.createElement("div");
    menuRow.className = "row";

    menuRow.appendChild(createMenuButton("Create 1,000 rows", "run"));
    menuRow.appendChild(createMenuButton("Create 10,000 rows", "runlots"));
    menuRow.appendChild(createMenuButton("Append 1,000 rows", "add"));
    menuRow.appendChild(createMenuButton("Update every 10th row", "update"));
    menuRow.appendChild(createMenuButton("Clear", "clear"));
    menuRow.appendChild(createMenuButton("Swap Rows", "swaprows"));

    menuDiv.appendChild(menuRow);

    jumbotronRow.appendChild(titleDiv);
    jumbotronRow.appendChild(menuDiv);

    jumbotron.appendChild(jumbotronRow);

    // table
    const table = document.createElement("table");
    table.className = "table table-hover table-striped test-data";
    const tbody = (this._tbody = document.createElement("tbody"));

    table.appendChild(tbody);

    const preloadIcon = document.createElement("span");
    preloadIcon.className = "preloadicon glyphicon glyphicon-remove";
    preloadIcon.setAttribute("aria-hidden", "true");

    container.appendChild(jumbotron);
    container.appendChild(table);
    container.appendChild(preloadIcon);

    this.appendChild(container);

    this.addEventListener("benchmark-action", (ev) => {
      const msg = ev.detail;
      const store = this._store;

      switch (msg.action) {
        case "run":
          store.run();
          this._removeAllRows();
          this._appendRows();
          break;
        case "runlots":
          store.runlots();
          this._removeAllRows();
          this._appendRows();
          break;
        case "add":
          store.add();
          this._appendRows();
          break;
        case "update": {
          store.update();
          const rows = this._rows;
          for (let i = 0; i < rows.length; i += 10) {
            rows[i].rowLabel = store.data[i].label;
          }
          break;
        }
        case "clear":
          store.clear();
          this._removeAllRows();
          break;
        case "swaprows": {
          const rows = this._rows;
          if (rows.length > 998) {
            store.swaprows();

            this._tbody.insertBefore(rows[998], rows[2]);
            this._tbody.insertBefore(rows[1], rows[999]);

            const tmp = rows[998];
            rows[998] = rows[1];
            rows[1] = tmp;
          }
          break;
        }
        case "delete": {
          const id = msg.payload;
          const i = this._findRowIndexById(id);
          store.delete(id);
          const row = this._rows[i];
          this._rows.splice(i, 1);
          if (this._selectedRow === row) {
            this._selectedRow = null;
          }
          row.remove();
          break;
        }
        case "select": {
          const id = msg.payload;
          store.select(id);
          if (this._selectedRow !== null) {
            this._selectedRow.rowSelected = false;
          }
          this._selectedRow = this._rows[this._findRowIndexById(id)];
          this._selectedRow.rowSelected = true;
          break;
        }
      }
    });
  }

  _findRowIndexById(id) {
    return this._store.data.findIndex((d) => d.id === id);
  }

  _removeAllRows() {
    this._selectedRow = null;
    this._rows = [];

    this._tbody.textContent = "";
  }

  _appendRows() {
    const tbody = this._tbody;
    const rows = this._rows;
    const storeData = this._store.data;

    for (let i = rows.length; i < storeData.length; i++) {
      const tr = createRow(storeData[i]);
      rows[i] = tr;
      tbody.appendChild(tr);
    }
  }
}

class BenchmarkRow extends HTMLTableRowElement {
  constructor() {
    super();
    this._rowId = null;
    this._rowLabel = null;
    this._rowSelected = false;

    const td1 = (this._td1 = td("col-md-1"));

    const td2 = td("col-md-4");
    const a2 = (this._a2 = document.createElement("a"));
    td2.appendChild(a2);

    const td3 = td("col-md-1");
    const a = document.createElement("a");

    const span = document.createElement("span");
    span.className = "glyphicon glyphicon-remove";
    span.setAttribute("aria-hidden", "true");

    a.appendChild(span);
    td3.appendChild(a);

    this.appendChild(td1);
    this.appendChild(td2);
    this.appendChild(td3);
    this.appendChild(td("col-md-6"));

    a.addEventListener("click", (ev) => {
      ev.preventDefault();
      this.dispatchEvent(
        new CustomEvent("benchmark-action", {
          bubbles: true,
          detail: { action: "delete", payload: this._rowId },
        })
      );
    });

    a2.addEventListener("click", (ev) => {
      ev.preventDefault();
      this.dispatchEvent(
        new CustomEvent("benchmark-action", {
          bubbles: true,
          detail: { action: "select", payload: this._rowId },
        })
      );
    });
  }

  get rowId() {
    return this._rowId;
  }

  set rowId(v) {
    this._td1.textContent = this._rowId = v;
  }

  get rowLabel() {
    return this._rowLabel;
  }

  set rowLabel(v) {
    this._a2.textContent = this._rowLabel = v;
  }

  get rowSelected() {
    return this._rowSelected;
  }

  set rowSelected(v) {
    if (this._rowSelected !== v) {
      this._rowSelected = v;
      this.className = v ? "danger" : "";
    }
  }
}

function createRow(data) {
  /**
   * @localvoid:
   *
   * There are two ways how to instantiate WebComponents: with a `new` operator and with `document.createElement()`
   * function. Instantiating WebComponents with a `new` operator has a slightly less overhead (probably because it
   * doesn't involve a hash map lookup to find a component).
   *
   * The main reason why I've used `document.createElement()` here is because it is an idiomatic way to instantiate
   * components in all popular frameworks that use WebComponents.
   */
  // const e = new BenchmarkRow();
  const e = document.createElement("tr", { is: "benchmark-row" });
  e.rowId = data.id;
  e.rowLabel = data.label;
  return e;
}

function td(className) {
  const td = document.createElement("td");
  td.className = className;
  return td;
}

class BenchmarkMenuButton extends HTMLDivElement {
  constructor() {
    super();
    this._action = null;
    this._content = null;

    const button = (this._button = document.createElement("button"));
    button.type = "button";
    button.className = "btn btn-primary btn-block";
    button.addEventListener("click", (ev) => {
      ev.preventDefault();
      this.dispatchEvent(new CustomEvent("benchmark-action", { bubbles: true, detail: { action: this._action } }));
    });

    this.className = "col-sm-6 smallpad";
    this.appendChild(button);
  }

  get action() {
    return this._action;
  }

  set action(v) {
    this._button.id = this._action = v;
  }

  get content() {
    return this._content;
  }

  set content(v) {
    this._button.textContent = this._content = v;
  }
}

function createMenuButton(title, action) {
  const e = document.createElement("div", { is: "benchmark-menu-button" });
  e.content = title;
  e.action = action;
  return e;
}

customElements.define("benchmark-menu-button", BenchmarkMenuButton, { extends: "div" });
customElements.define("benchmark-row", BenchmarkRow, { extends: "tr" });
customElements.define("benchmark-app", BenchmarkApp, { extends: "div" });
