// js-framework-benchmark/frameworks/keyed/preact-classes/src/Main.jsx
"use strict";

var preact = require("preact");
var { render, h, Component } = preact;
const { Row } = require("./Row");
const { Store } = require("./Store");

export class Main extends Component {
  constructor(props) {
    super(props);
    this.state = { store: new Store() };
    this.select = this.select.bind(this);
    this.delete = this.delete.bind(this);
    this.add = this.add.bind(this);
    this.run = this.run.bind(this);
    this.update = this.update.bind(this);
    this.runlots = this.runlots.bind(this);
    this.clear = this.clear.bind(this);
    this.swaprows = this.swaprows.bind(this);
    this.start = 0;
    this.length = 0;

    window.app = this;
  }
  run() {
    this.state.store.run();
    this.setState({ store: this.state.store });
  }
  add() {
    this.state.store.add();
    this.setState({ store: this.state.store });
  }
  update() {
    this.state.store.update();
    this.setState({ store: this.state.store });
  }
  select(id) {
    this.state.store.select(id);
    this.setState({ store: this.state.store });
  }
  delete(id) {
    this.state.store.delete(id);
    this.setState({ store: this.state.store });
  }
  runlots() {
    this.state.store.runlots();
    this.setState({ store: this.state.store });
  }
  clear() {
    this.state.store.clear();
    this.setState({ store: this.state.store });
  }
  swaprows() {
    this.state.store.swaprows();
    this.setState({ store: this.state.store });
  }
  render() {
    let rows = this.state.store.data.map((d, i) => {
      return (
        <Row
          key={d.id}
          data={d}
          onClick={this.select}
          onDelete={this.delete}
          styleClass={d.id === this.state.store.selected ? "danger" : ""}
        ></Row>
      );
    });
    return (
      <div className="container">
        <div className="jumbotron">
          <div className="row">
            <div className="col-md-6">
              <h1>preact</h1>
            </div>
            <div className="col-md-6">
              <div className="row">
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="run" onClick={this.run}>
                    Create 1,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="runlots" onClick={this.runlots}>
                    Create 10,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="add" onClick={this.add}>
                    Append 1,000 rows
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="update" onClick={this.update}>
                    Update every 10th row
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="clear" onClick={this.clear}>
                    Clear
                  </button>
                </div>
                <div className="col-sm-6 smallpad">
                  <button type="button" className="btn btn-primary btn-block" id="swaprows" onClick={this.swaprows}>
                    Swap Rows
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <table className="table-hover table-striped test-data table">
          <tbody>{rows}</tbody>
        </table>
        <span className="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
      </div>
    );
  }
}

render(<Main />, document.getElementById("main"));

// js-framework-benchmark/frameworks/keyed/lit/src/main.ts
import { LitElement, html } from "lit";
import { property, customElement } from "lit/decorators.js";
import { repeat } from "lit/directives/repeat.js";
import { Store } from "./store";

const store = new Store();

@customElement("main-element")
export class MainElement extends LitElement {
  @property()
  _rows = store.data;

  @property()
  _selected = store.selected;

  render() {
    return html`
      <link href="/css/currentStyle.css" rel="stylesheet" />
      <div class="container">
        <div class="jumbotron">
          <div class="row">
            <div class="col-md-6">
              <h1>Lit keyed</h1>
            </div>
            <div class="col-md-6">
              <div class="row">
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="run" @click=${this._run}>
                    Create 1,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="runlots" @click=${this._runlots}>
                    Create 10,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="add" @click=${this._add}>
                    Append 1,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="update" @click=${this._update}>
                    Update every 10th row
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="clear" @click=${this._clear}>
                    Clear
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="swaprows" @click=${this._swaprows}>
                    Swap Rows
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <table class="table-hover table-striped test-data table" @click=${this._handleClick}>
          <tbody>
            ${repeat(
              this._rows,
              (item) => item.id,
              (item) =>
                html` <tr id=${item.id} class=${item.id == this._selected ? "danger" : ""}>
                  <td class="col-md-1">${item.id}</td>
                  <td class="col-md-4">
                    <a data-action="select" data-id=${item.id}>${item.label}</a>
                  </td>
                  <td class="col-md-1">
                    <a>
                      <span
                        class="glyphicon glyphicon-remove"
                        aria-hidden="true"
                        data-action="remove"
                        data-id=${item.id}
                      ></span>
                    </a>
                  </td>
                  <td class="col-md-6"></td>
                </tr>`
            )}
          </tbody>
        </table>
        <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
      </div>
    `;
  }

  _handleClick(e) {
    const { action, id } = e.target.dataset;
    if (action && id) {
      this["_" + action](id);
    }
  }
  _add() {
    store.add();
    this._sync();
  }
  _remove(id) {
    store.delete(id);
    this._sync();
  }
  _select(id) {
    store.select(id);
    this._sync();
  }
  _run() {
    store.run();
    this._sync();
  }
  _update() {
    store.update();
    this._sync();
  }
  _runlots() {
    store.runlots();
    this._sync();
  }
  _clear() {
    store.clear();
    this._sync();
  }
  _swaprows() {
    store.swaprows();
    this._sync();
  }
  _sync() {
    this._rows = store.data;
    this._selected = store.selected;
  }
}
