// js-framework-benchmark/frameworks/non-keyed/lit/src/main.ts
import { LitElement, html } from "lit";
import { property, customElement } from "lit/decorators.js";
import { Store } from "./store";

const store = new Store();

@customElement("main-element")
export class MainElement extends LitElement {
  @property()
  _rows = store.data;

  @property()
  _selected = store.selected;

  render() {
    return html`
      <link href="/css/currentStyle.css" rel="stylesheet" />
      <div class="container">
        <div class="jumbotron">
          <div class="row">
            <div class="col-md-6">
              <h1>Lit non-keyed</h1>
            </div>
            <div class="col-md-6">
              <div class="row">
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="run" @click=${this._run}>
                    Create 1,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="runlots" @click=${this._runlots}>
                    Create 10,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="add" @click=${this._add}>
                    Append 1,000 rows
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="update" @click=${this._update}>
                    Update every 10th row
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="clear" @click=${this._clear}>
                    Clear
                  </button>
                </div>
                <div class="col-sm-6 smallpad">
                  <button type="button" class="btn btn-primary btn-block" id="swaprows" @click=${this._swaprows}>
                    Swap Rows
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <table class="table-hover table-striped test-data table" @click=${this._handleClick}>
          <tbody>
            ${this._rows.map(
              (item) =>
                html` <tr id=${item.id} class=${this._selected == item.id ? "danger" : ""}>
                  <td class="col-md-1">${item.id}</td>
                  <td class="col-md-4">
                    <a data-action="select" data-id=${item.id}>${item.label}</a>
                  </td>
                  <td class="col-md-1">
                    <a>
                      <span
                        class="glyphicon glyphicon-remove"
                        aria-hidden="true"
                        data-action="remove"
                        data-id=${item.id}
                      ></span>
                    </a>
                  </td>
                  <td class="col-md-6"></td>
                </tr>`
            )}
          </tbody>
        </table>
        <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
      </div>
    `;
  }

  _handleClick(e) {
    const { action, id } = e.target.dataset;
    if (action && id) {
      this["_" + action](id);
    }
  }
  _add() {
    store.add();
    this._sync();
  }
  _remove(id) {
    store.delete(id);
    this._sync();
  }
  _select(id) {
    store.select(id);
    this._sync();
  }
  _run() {
    store.run();
    this._sync();
  }
  _update() {
    store.update();
    this._sync();
  }
  _runlots() {
    store.runlots();
    this._sync();
  }
  _clear() {
    store.clear();
    this._sync();
  }
  _swaprows() {
    store.swaprows();
    this._sync();
  }
  _sync() {
    this._rows = store.data;
    this._selected = store.selected;
  }
}

// js-framework-benchmark/frameworks/keyed/preact-kr-observable/src/Main.jsx
import { render } from "preact";
import { observer } from "kr-observable/preact";
import { Row } from "./Row";
import { rowsStore } from "./RowsStore";

const Button = ({ children, id, onClick }) => {
  return (
    <div className="col-sm-6 smallpad">
      <button type="button" className="btn btn-primary btn-block" id={id} onClick={onClick}>
        {children}
      </button>
    </div>
  );
};

const RowList = observer(function list() {
  return rowsStore.rows.map((row) => <Row key={row.id} data={row} />);
});

function Main() {
  return (
    <div className="container">
      <div className="jumbotron">
        <div className="row">
          <div className="col-md-6">
            <h1>Preact + kr-observable</h1>
          </div>

          <div className="col-md-6">
            <div className="row">
              <Button id="run" onClick={rowsStore.run}>
                Create 1,000 rows
              </Button>

              <Button id="runlots" onClick={rowsStore.runlots}>
                Create 10,000 rows
              </Button>

              <Button id="add" onClick={rowsStore.add}>
                Append 1,000 rows
              </Button>

              <Button id="update" onClick={rowsStore.update}>
                Update every 10th row
              </Button>

              <Button id="clear" onClick={rowsStore.clear}>
                Clear
              </Button>

              <Button id="swaprows" onClick={rowsStore.swaprows}>
                Swap Rows
              </Button>
            </div>
          </div>
        </div>
      </div>

      <table className="table-hover table-striped test-data table">
        <tbody>
          <RowList />
        </tbody>
      </table>

      <span className="preloadicon glyphicon glyphicon-remove" aria-hidden="true" />
    </div>
  );
}

render(<Main />, document.getElementById("main"));
